In [ ]:
import sys

In [ ]:
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install gym

In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
from gym.envs.toy_text.frozen_lake import generate_random_map


In [ ]:
env = gym.make("FrozenLake-v1")
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes = 20000
max_steps_per_episode = 100

learning_rate = 0.035
discount_rate = 0.975

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = []

# Q-Learning algorithm
for episode in range(num_episodes):
    
    # random_map = generate_random_map(size=4, p=0.8)
    # env = gym.make("FrozenLake-v0", desc=random_map)
    env = gym.make("FrozenLake-v1")
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range (max_steps_per_episode):

        # Exploration / Exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate reward across all episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("*** AVG reward per 1000 episodes***\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print Q table
print("\n\n *** Q-table ***\n")
print(q_table)
    

*** AVG reward per 1000 episodes***

1000 :  0.026000000000000016
2000 :  0.06500000000000004
3000 :  0.1590000000000001
4000 :  0.23500000000000018
5000 :  0.4850000000000004
6000 :  0.5880000000000004
7000 :  0.6260000000000004
8000 :  0.5920000000000004
9000 :  0.6070000000000004
10000 :  0.5760000000000004
11000 :  0.5960000000000004
12000 :  0.5900000000000004
13000 :  0.6170000000000004
14000 :  0.6020000000000004
15000 :  0.5630000000000004
16000 :  0.6160000000000004
17000 :  0.5990000000000004
18000 :  0.5780000000000004
19000 :  0.6090000000000004
20000 :  0.5920000000000004


 *** Q-table ***

[[0.27295883 0.22339212 0.22712725 0.21504352]
 [0.07682355 0.07588342 0.07226097 0.19273188]
 [0.13194979 0.07817779 0.07425089 0.06450226]
 [0.04044351 0.00159734 0.00338564 0.00760513]
 [0.29449174 0.16843127 0.19268514 0.15775992]
 [0.         0.         0.         0.        ]
 [0.13021823 0.08076763 0.08134836 0.01489293]
 [0.         0.         0.         0.        ]
 [0.16078604

In [496]:
# random_map = generate_random_map(size=4, p=0.8)
# env = gym.make("FrozenLake-v0", desc=random_map)
env = gym.make("FrozenLake-v1")
for episode in range(1):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
