In [510]:
import sys

In [511]:
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install gym

In [512]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output
from gym.envs.toy_text.frozen_lake import generate_random_map


In [513]:
env = gym.make("FrozenLake-v1")
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [514]:
num_episodes = 20000
max_steps_per_episode = 100

learning_rate = 0.035 #Between 0 and 1. How quickly the agent abandons the previous value in the Q table for the new value. 0: Agent learns nothing and only uses prior knowledge. 1: Agent considers only the most recent information.
discount_rate = 0.975

exploration_rate = 1
max_exploration_rate = 1    #1: Guaranteed that agent starts the game by 100% exploring the environment
min_exploration_rate = 0    #0: Agent does not explore at all. Agent only exploits (chooses actions to get max points)
exploration_decay_rate = 0.001

In [515]:
rewards_all_episodes = []

# Q-Learning algorithm
for episode in range(num_episodes):
    
    # random_map = generate_random_map(size=4, p=0.8)
    # env = gym.make("FrozenLake-v0", desc=random_map)
    env = gym.make("FrozenLake-v1")
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range (max_steps_per_episode):

        # Exploration / Exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate reward across all episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("*** AVG reward per 1000 episodes***\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print Q table
print("\n\n *** Q-table ***\n")
print(q_table)
    

*** AVG reward per 1000 episodes***

1000 :  0.04300000000000003
2000 :  0.20500000000000015
3000 :  0.4180000000000003
4000 :  0.6140000000000004
5000 :  0.6730000000000005
6000 :  0.7190000000000005
7000 :  0.7080000000000005
8000 :  0.7330000000000005
9000 :  0.7290000000000005
10000 :  0.7220000000000005
11000 :  0.7580000000000006
12000 :  0.7270000000000005
13000 :  0.7500000000000006
14000 :  0.7060000000000005
15000 :  0.7040000000000005
16000 :  0.7110000000000005
17000 :  0.7280000000000005
18000 :  0.7040000000000005
19000 :  0.7230000000000005
20000 :  0.7460000000000006


 *** Q-table ***

[[0.34901102 0.26842667 0.26889529 0.26929462]
 [0.1007994  0.12905103 0.08448711 0.29778514]
 [0.26756757 0.13238056 0.09718807 0.11087794]
 [0.04899919 0.00874311 0.00143245 0.01159052]
 [0.3728713  0.28759422 0.2151017  0.24684098]
 [0.         0.         0.         0.        ]
 [0.15131197 0.05930552 0.21061772 0.04260296]
 [0.         0.         0.         0.        ]
 [0.28773829 0

In [509]:
# random_map = generate_random_map(size=4, p=0.8)
# env = gym.make("FrozenLake-v0", desc=random_map)
env = gym.make("FrozenLake-v1")
for episode in range(1):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
